"""add_lora_training_tables

Revision ID: 75ca77cca0fd
Revises: d0d2e12a2242
Create Date: 2026-03-06 22:05:11.032670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ca77cca0fd'
down_revision: Union[str, Sequence[str], None] = 'd0d2e12a2242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_lora_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('tuning_job_id', sa.String(length=500), nullable=False),
    sa.Column('model_endpoint', sa.String(length=500), nullable=True),
    sa.Column('model_name', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'training', 'succeeded', 'failed', name='loramodelstatus'), nullable=False),
    sa.Column('training_samples_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_lora_models_student_id', 'student_lora_models', ['student_id'], unique=False)
    op.create_table('student_training_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('image_gcs_uri', sa.Text(), nullable=False),
    sa.Column('ground_truth_latex', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_training_samples_student_id', 'student_training_samples', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_training_samples_student_id', table_name='student_training_samples')
    op.drop_table('student_training_samples')
    op.drop_index('ix_student_lora_models_student_id', table_name='student_lora_models')
    op.drop_table('student_lora_models')
    # ### end Alembic commands ###
